In [1]:
import pandas as pd

In [2]:
# AQI data set
df = pd.read_csv("globalAirQuality.csv")

In [3]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [4]:
# Selecting data
# selecting columns
df["country"]
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [5]:
# Selecting rows
# Select rows (by label)
df.loc[0]             # 1st row (by label)
df.loc[0:3]           # row0 to row3 - both inclusive in loc

# Select rows (by index)
df.iloc[0]            # 1st row 
df.iloc[4:7]          # row4 to row6 - ending row exclusive in iloc

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
5,2025-11-04 23:25:17.554219,US,New York,40.713,-74.006,31.242,92.779,30.633,8.030,43.725,0.347,92,15.159,42.505,1.199
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542

In [6]:
# Select rows & columns
df.loc[0, "country"]  # 0th row & specific column
df.iloc[0, 2]         # 1th row & 3rd column (by position)

df.iloc[0, 1:5]
df.loc[0, ["country", "aqi"]]

df.loc[0:5, ["country", "city", "latitude"]]   # end is inclusive
df.iloc[0:5, [1, 3, 6, 10]]                    # end is exclusive

  country  latitude     pm10     co
0      US    40.713  108.938  1.096
1      US    40.713   63.043  1.075
2      US    40.713   82.553  0.977
3      US    40.713   79.951  0.230
4      US    40.713   66.423  1.085

In [7]:
# Select single scalar value
df.at[0, "city"]
df.iat[0, 2]

'New York'

In [8]:
# Filtering Data
df[df["aqi"]>100] #print rows where aqi > 100
df[df["aqi"]>100][["aqi", "city"]] #print rows where aqi > 100 and columns only aqi, city

df[(df["aqi"]>100) & (df["timestamp"] == "2025-11-04 18:25:17.554219")]
aqi_data = df[(df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]


aqi_data.iloc[0]
# aqi_data.loc[0] # Error => not exist label 0 in aqi_data
aqi_data.loc[6] # show data of first row as like aqi_data.iloc.[0]

# Query - returns a copy, not a view
aqi_val = 100
df.query("aqi > 100")
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]]
df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [9]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403