In [4]:
import pandas as pd

In [11]:
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

# merge
pd.merge(df_customers, df_orders, on = "customer_id") # inner join
pd.merge(df_customers, df_orders, on = "customer_id", how = "left") # left join
pd.merge(df_customers, df_orders, on = "customer_id", how = "right") # right join
pd.merge(df_customers, df_orders, on = "customer_id", how = "outer") # outer join

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [6]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

In [7]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [20]:
# Concatenation
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Bob", "Charlie"]
})

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["David", "Eva", "Frank"]
})

pd.concat([df1, df2]) # on top (row wise concatination)
pd.concat([df1, df2], ignore_index = True)  # row wise concatination - new index
pd.concat([df1, df2], axis = 1) # side by side ( col wise concatination)

   id     name  id   name
0   1     Adam   4  David
1   2      Bob   5    Eva
2   3  Charlie   6  Frank

In [15]:
df1

   id     name
0   1     Adam
1   2      Bob
2   3  Charlie

In [16]:
df2

   id   name
0   4  David
1   5    Eva
2   6  Frank